name: "Build And Push Docker Image To Docker Hub Registry With Date Tag And Latest Tag"

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'The name of the docker image to push (e.g. my-app)'
        type: string
        required: true
    secrets:
      docker-username:
        description: 'The username of the Docker Hub account'
        required: true
      docker-token:
        description: 'The token of the Docker Hub account'
        required: true


jobs:
    build-and-push:
      runs-on: ubuntu-latest

      steps:
        - name: Set Env Tag
          run: echo "NOW=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.docker-username }}
              password: ${{ secrets.docker-token }}
        - name: Build Push To Docker Hub
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: |
                ${{secrets.docker-username}}/${{ inputs.docker-image-name }}:${{ env.NOW }}
                ${{secrets.docker-username}}/${{ inputs.docker-image-name }}:latest